files:
  - source: /src/main/resources/assets/*/lang/en_us.lang
    translation: /%original_path%/%locale_with_underscore%.lang
  - source: /*/src/main/resources/assets/*/lang/en_us.json
    translation: /%original_path%/%locale_with_underscore%.json
