# Mods.toml for the devices mod by ultreon (originally created my MrCrayfish)
# Copyright (c) 2022 - Ultreon Team, GPLv3 License. See the license at https://www.gnu.org/licenses/gpl-3.0-standalone.html

modLoader = "javafml"
loaderVersion = "*"
license = "GPL-3.0"
#issueTrackerURL = "https://github.com/Ultreon/devices-mod/issues"

# The main mod, and all sub-mods.
[[mods]]
modId = "devices_forge"
version = "0.0.0-generated"
displayName = "(Wrapper) Devices Mod"
description = '''
Forge wrapper for devices mod
'''
itemIcon = "minecraft:red_wool"

[[dependencies.devices_forge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.19.4)"
ordering = "NONE"
side = "BOTH"

[[dependencies.devices_forge]]
modId = "architectury"
mandatory = true
versionRange = "[7.1,8)"
ordering = "NONE"
side = "BOTH"
