# Mods.toml for the devices mod by ultreon (originally created my MrCrayfish)
# Copyright (c) 2022 - Ultreon Team, GPLv3 License. See the license at https://www.gnu.org/licenses/gpl-3.0-standalone.html
modLoader = "javafml"
loaderVersion = "*"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/Ultreon/devices-mod/issues"

# The main mod, and all sub-mods.
[[mods]]
modId = "devices_forge"
description = '''
Forge wrapper for devices mod
'''
itemIcon = "minecraft:red_wool"

# Dependencies for the main mod.
[[dependencies.devices_forge]]
modId = "forge"
mandatory = true
versionRange = "[40.1.60,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.devices_forge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.devices_forge]]
modId = "architectury"
mandatory = true
versionRange = "[4.5.76,5.0)"
ordering = "NONE"
side = "BOTH"
